/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.antlers.html',
        './resources/**/*.antlers.php',
        './resources/**/*.blade.php',
        './resources/**/*.vue',
        './content/**/*.md',
        'node_modules/preline/dist/*.js',
    ],

    theme: {
        extend: {
            fontFamily: {
                'sans': ['Avenir', 'system-ui', 'sans-serif'],
                avenir: ['Avenir', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                'xs': ['0.75rem', { lineHeight: '1rem' }],
                'sm': ['0.875rem', { lineHeight: '1.25rem' }],
                'base': ['1rem', { lineHeight: '1.5rem' }],
                'lg': ['1.125rem', { lineHeight: '1.75rem' }],
                'xl': ['1.25rem', { lineHeight: '1.75rem' }],
                '2xl': ['1.5rem', { lineHeight: '2rem' }],
                '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
                '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
                '5xl': ['3rem', { lineHeight: '1' }],
                '6xl': ['3.75rem', { lineHeight: '1' }],
            },
            letterSpacing: {
                'tighter': '-0.05em',
                'tight': '-0.025em',
                'normal': '0',
                'wide': '0.025em',
                'wider': '0.05em',
                'widest': '0.1em',
            },
            lineHeight: {
                'none': '1',
                'tight': '1.25',
                'snug': '1.375',
                'normal': '1.5',
                'relaxed': '1.625',
                'loose': '2',
            },
            colors: {
                'primary': '#FFE9EB',
                'secondary': '#FBDFE2',
                'warmred': '#DE4353',
                'warmred-light': '#F56573',
                'warmred-dark': '#C73A4A',
                'warmblack': '#181B18',
                'warmblack-light': '#2A2D2A',
                'warmgray': '#2F302F',
                'warmgray-light': '#404140',
                'brown': '#4D4243',
                'brown-light': '#5D5253',
                'accent': '#FF6B6B',
                'accent-light': '#FF8E8E',
                'neutral': '#F8F9FA',
                'neutral-dark': '#E9ECEF',
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
                'gradient-warm': 'linear-gradient(135deg, #FFE9EB 0%, #FBDFE2 100%)',
                'gradient-dark': 'linear-gradient(135deg, #181B18 0%, #2F302F 100%)',
                'gradient-red': 'linear-gradient(135deg, #DE4353 0%, #F56573 100%)',
            },
            boxShadow: {
                'warm': '0 10px 25px -5px rgba(222, 67, 83, 0.1), 0 10px 10px -5px rgba(222, 67, 83, 0.04)',
                'warm-lg': '0 20px 25px -5px rgba(222, 67, 83, 0.1), 0 10px 10px -5px rgba(222, 67, 83, 0.04)',
                'glow': '0 0 20px rgba(222, 67, 83, 0.3)',
                'glow-lg': '0 0 40px rgba(222, 67, 83, 0.4)',
            },
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
        require('preline/plugin'),
    ],
};
