title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: main_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: 'Main image'
          -
            handle: summary
            field:
              remove_empty_nodes: false
              type: bard
              display: Summary
          -
            handle: role
            field:
              type: text
              display: Role
          -
            handle: team
            field:
              type: text
              display: Team
          -
            handle: intro_images
            field:
              container: assets
              type: assets
              display: 'Intro images'
          -
            handle: movie
            field:
              type: video
              display: Movie
          -
            handle: content_area
            field:
              type: replicator
              display: 'Content area'
              sets:
                new_set_group:
                  display: 'New Set Group'
                  sets:
                    text:
                      display: Text
                      fields:
                        -
                          handle: text
                          field:
                            remove_empty_nodes: false
                            type: bard
                            display: Text
                    image:
                      display: Image
                      fields:
                        -
                          handle: image
                          field:
                            container: assets
                            type: assets
                            display: Image
                            max_files: 1
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
          -
            handle: coming_soon
            field:
              type: toggle
              display: 'Coming Soon'
          -
            handle: tags
            field:
              type: terms
              taxonomies:
                - tags
              display: tags
              mode: select
